### ISSUE TITLE
Unable to build using Cocoapods

### ISSUE THREAD

**Issue by marcbaldwin** [RxSwiftCommunity/RxGoogleMaps#10]
Hi there,

I'm unable to build the project, with the error reported 'No such module RxSwift'

Any ideas what could be wrong?

My Podfile looks something like this...

```
platform :ios, '9.0'
use_frameworks!

...

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'GoogleMaps'
  pod 'RxGoogleMaps', :git => 'https://github.com/RxSwiftCommunity/RxGoogleMaps', :commit => 'b182d08'
```

**Comment by freak4pc** [comment]
Hey @marcbaldwin, 

This isn't specifically a RxGoogleMaps issue. It seems for some reason RxSwift doesn't build correctly.
Two things - 

1. You don't need the "commit" part, just live the `:git` clause there
2. do a fresh pod install, clean your Xcode project and build from scratch. That should work just fine in this case :)

**Comment by marcbaldwin** [comment]
Hey thanks for the reply,

I've tried a fresh pod install, also a pod deintegrate and no luck.

It also errors with  'No such module GoogleMaps'.

I think it could be related to the fact this pod is a static library, but I have no idea how to solve it.

**Comment by freak4pc** [comment]
Do you have CocoaPods 1.4.0 and up? https://github.com/RxSwiftCommunity/RxGoogleMaps#cocoapods

**Comment by marcbaldwin** [comment]
Yeah using 1.4.0.beta.1

**Comment by freak4pc** [comment]
Uhm no issues on my end. Very odd. (empty project, just that pod there)

<img width="468" alt="894c4bd7-9f67-4fd9-ab67-478935b96595" src="https://user-images.githubusercontent.com/605076/34180615-0d9d17c0-e518-11e7-8e1a-082adb73749a.png">

Podfile is: 
```
target 'TestGoogle' do
  use_frameworks!
  pod 'RxGoogleMaps', :git => 'https://github.com/RxSwiftCommunity/RxGoogleMaps'
end
```
