### ISSUE TITLE
Can you please upload a new release with RxSwift compatibility ? 

### ISSUE THREAD

**Issue by danielReporty** [RxSwiftCommunity/RxGoogleMaps#11]
Can you please upload a new release with RxSwift compatibility ? 
The master seems to have this code, but no release was published.

**Comment by freak4pc** [comment]
@inkyfox do you mind helping out by either adding a new release, or even better add me as a contributor on the Cocoapod so I can push some releases myself? 

@danielReporty You can direct your Podfile directly to the repo and master branch for now: 

`pod 'RxGoogleMaps', :git => 'https://github.com/RxSwiftCommunity/RxGoogleMaps'`

**Comment by danielReporty** [comment]
OK.
I get this error on pod install:

[!] The 'Pods-Reporty' target has transitive dependencies that include static binaries: (/XXXX/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /XXXX/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, and /XXXX/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework)

**Comment by freak4pc** [comment]
Please look at the README and confirm you have the correct Cocoapods version. Only the latest pre supports static framework installation.

**Comment by cooksimo** [comment]
Am I missing something? There is still not a pod published that is compatible with the latest RxSwift

**Comment by freak4pc** [comment]
@cooksimo You're not missing anything. The original author of the Cocoapod has vanished so we have no one with actual permission to push a podspec. We're still trying to figure out how we can resolve these sort of scenarios (see https://github.com/RxSwiftCommunity/contributors/issues/31 )

You'll have to use the method in the second comment here (direct your Podfile directly to the repo), for now, unfortunately.

@orta are you aware of any process we could use to push a spec up or "ask" for ownership transfer on this repo? I've pinged the author several times but he's not responsive.
