### ISSUE TITLE
Carthage support doesn't work

### ISSUE THREAD

**Issue by cooksimo** [RxSwiftCommunity/RxGoogleMaps#17]
Is installation of this project via Carthage expected to work? It seems like it is/was supported since there is a Cartfile in the repo, but without installing the Pods, Carthage cannot build the project.

**Comment by freak4pc** [comment]
@cooksimo I don't entirely know since I don't personally use Carthage but if you'd like to push a PR to fix this I'd love to review it :) Thanks !
