### ISSUE TITLE
I didn't found 'RxGoogleMapsBridge' in pods project

### ISSUE THREAD

**Issue by Henawey** [RxSwiftCommunity/RxGoogleMaps#2]

**Comment by shams-ahmed** [comment]
@Henawey it's called `pod "RxGoogleMaps"`

**Comment by Henawey** [comment]
I mean I don't find Bridge file in Pods to add it to my target
![screen shot 2017-01-27 at 3 21 00 am](https://cloud.githubusercontent.com/assets/1625484/22357297/b6b2e310-e43f-11e6-91a4-fce8285fa969.png)

**Comment by inkyfox** [comment]
@Henawey 
Sorry for late.
It's located in the directory of ''Pods/RxGoogleMaps/RxGoogleMapsBridge.swift'' and it's not seen at XCode at first. So you should add it to your project manually.
Thank you.

**Comment by Henawey** [comment]
Thanks
