### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by edon2005** [RxSwiftCommunity/RxGoogleMaps#22]
HI guys,

Thanks for your Framework,
I have a small question. How to use it with Clustering that is in Google-Maps-iOS-Utils? 
Because clustering provide something like that:
```
 clusterManager.setDelegate(self, mapDelegate: self)
```

and this "destroyed" connection with RxGoogleMaps.

Thanks.

**Comment by freak4pc** [comment]
Hey @edon2005 
I don't believe you could use such an external library with this as this cluster manager requires holding the delegate that is already set by RxGoogleMaps. 

I don't have a super great idea to help with this as both libraries take over the delegate. 

We could add a forward delegate (like `mapView.rx.setDelegate(self)`) but this is really the "other way around" and would still not let you use this IMO.

**Comment by edon2005** [comment]
Thanks for quick response!
