### ISSUE TITLE
Not able to install version 3.1.0 via Cocoapods

### ISSUE THREAD

**Issue by aksswami** [RxSwiftCommunity/RxGoogleMaps#24]
Podfile :- 

`pod 'RxGoogleMaps', '~> 3.1.0'`

Output :- 

```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RxGoogleMaps":
  In Podfile:
    RxGoogleMaps (~> 3.1.0)

None of your spec sources contain a spec satisfying the dependency: `RxGoogleMaps (~> 3.1.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Cocoapods version:- 1.5.3, Xcode 10, Swift 4.2

**Comment by freak4pc** [comment]
Thanks Amit
Can you point your Podfile directly to the repos master branch to see if
that works for you?

-- 
Shai Mishali

**Comment by aksswami** [comment]
@freak4pc Using git remote directly to `master` branch works fine and updates the pod to `3.1.0` with GoogleMap to `2.7.0` as expected.
`  pod 'RxGoogleMaps', :git => 'https://github.com/RxSwiftCommunity/RxGoogleMaps', :branch => 'master'`

But why this not working with `pod 'RxGoogleMaps', '~> 3.1.0'`. 
I have also updated the cocoapods repo with `pod repo update` to get the latest indexes.

**Comment by freak4pc** [comment]
Hey - the latest version is 3.0.1, not 3.1.0. Can you try again and confirm? 

Thanks
Shai

**Comment by freak4pc** [comment]
Just released the pod.

**Comment by aksswami** [comment]
Thanks @freak4pc.
