### ISSUE TITLE
Carthage error (question)

### ISSUE THREAD

**Issue by romanfurman6** [RxSwiftCommunity/RxGoogleMaps#5]
Hey can u help me please :) 
`carthage update RxGoogleMaps`
`Skipped building RxGoogleMaps due to the error:
Dependency "RxGoogleMaps" has no shared framework schemes`
 tell me what I'm doing wrong ;(
i try add to cartfile
`github "RxSwiftCommunity/RxGoogleMaps" "master"`
`github "RxSwiftCommunity/RxGoogleMaps" ~> 2.2.0`

**Comment by scottrhoyt** [comment]
Hey @romanfurman6. Doesn't look like RxGoogleMaps officially supports Carthage. Here is my suggestion:

* Fork the repo
* Share the appropriate scheme to build the framework
* in the project directory do a `carthage build --no-skip-current` to verify the framework builds
* if so use your fork for carthage and submit a PR back here for adding Carthage support.

Let me know if you have any questions on that.

**Comment by romanfurman6** [comment]
@scottrhoyt hey, thanks for answer.
I try it, thanks once again ;)

**Comment by romanfurman6** [comment]
@scottrhoyt Hey, I can't add carthage support for RxGMs because GM don't support it, maybe i misunderstand something.

**Comment by scottrhoyt** [comment]
Hmm... I think that should mainly be a function of where RxGoogleMaps is configured to look for frameworks. But even then it would still be messy to have a dependency that can't be installed by the same dependency manager. Probably best to not introduce that then. Carthage has recently added support for binary-only downloads, so hopefully Google will add support in time.
